#%RAML 1.0 DataType

additionalProperties: false
properties:
  errors:
    type: object
    properties:
      id:
        type: number
      code: 
        type: string
      status:
        type: number
      title: 
        type: string
      detail:
        type: string
      href: 
        type: string
      checked:
        type: boolean