#%RAML 1.0 DataType

additionalProperties: false
properties:
  name:
    type: string
    description: key
    example: 'template01'
  content:
    type: string
    description: value
    example: '[{"processId": "ontario-inventory-tbg","version": "1.0.0","name": "Process mail files data load"}]'